openapi: 3.0.1
info:
  title: HubSpot Marketing
  version: v3
servers:
- url: https://api.hubapi.com
paths:
  /marketing/v3/emails/:
    get:
      tags:
      - Marketing Emails
      summary: Get all marketing emails for a HubSpot account.
      description: The results can be filtered, allowing you to find a specific set
        of emails. See the table below for a full list of filtering options.
      operationId: GetListMarketingEmails
      security:
      - private_apps_legacy:
        - content
      - oauth2_legacy:
        - content
    post:
      tags:
      - Marketing Emails
      summary: Create a new marketing email.
      description: Use this endpoint to create a new marketing email.
      operationId: CreateMarketingEmail
      security:
      - private_apps_legacy:
        - content
      - oauth2_legacy:
        - content
  /marketing/v3/emails/{emailId}:
    get:
      tags:
      - Marketing Emails
      summary: Get the details of a specified marketing email.
      description: Get the details for a marketing email.
      operationId: GetMarketingEmailById
      security:
      - private_apps_legacy:
        - content
      - oauth2_legacy:
        - content
    delete:
      tags:
      - Marketing Emails
      summary: Delete a marketing email.
      operationId: DeleteMarketingEmailById
      security:
      - private_apps_legacy:
        - content
      - oauth2_legacy:
        - content
    patch:
      tags:
      - Marketing Emails
      summary: Update a marketing email.
      description: Change properties of a marketing email.
      operationId: UpdateMarketingEmailById
      security:
      - private_apps_legacy:
        - content
      - oauth2_legacy:
        - content
  /marketing/v3/marketing-events/participations/{marketingEventId}/breakdown:
    get:
      tags:
      - Participant State
      summary: Read participations breakdown by Marketing Event internal identifier
      description: Read Marketing event's participations breakdown with optional filters
        by internal identifier marketingEventId.
      operationId: GetParticipationBreakdownForMarketingEventById
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      - private_apps_legacy:
        - crm.objects.marketing_events.read
  /marketing/v3/marketing-events/participations/{marketingEventId}:
    get:
      tags:
      - Participant State
      summary: Read participations counters by Marketing Event internal identifier
      description: Read Marketing event's participations counters by internal identifier
        marketingEventId.
      operationId: GetParticipationCountersForMarketingEventById
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      - private_apps_legacy:
        - crm.objects.marketing_events.read
  /marketing/v3/marketing-events/events/delete:
    post:
      tags:
      - Basic
      summary: Delete multiple marketing events
      description: Bulk delete a number of marketing events in HubSpot
      operationId: DeleteMarketingEventsById
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
  /marketing/v3/marketing-events/events/upsert:
    post:
      tags:
      - Basic
      summary: Create or update multiple marketing events
      description: Upsert multiple marketing events. If there is an existing Marketing
        event with the specified ID, it will be updated; otherwise a new event will
        be created.
      operationId: CreateOrUpdateMarketingEventsById
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
  /marketing/v3/marketing-events/events:
    post:
      tags:
      - Basic
      summary: Create a marketing event
      description: Creates a new marketing event in HubSpot
      operationId: CreateMarketingEvent
      security:
      - private_apps_legacy:
        - crm.objects.marketing_events.write
      - oauth2_legacy:
        - crm.objects.marketing_events.write
  /marketing/v3/marketing-events/participations/contacts/{contactIdentifier}/breakdown:
    get:
      tags:
      - Participant State
      summary: Read participations breakdown by Contact identifier
      description: Read Contact's participations by identifier - email or internal
        id.
      operationId: GetContactParticipationBreakdownForMarketingEventById
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      - private_apps_legacy:
        - crm.objects.marketing_events.read
  /marketing/v3/marketing-events/{appId}/settings:
    get:
      tags:
      - Settings
      summary: Retrieve the application settings
      description: Retrieve the current settings for the application.
      operationId: GetMarketingEventSettings
      security:
      - developer_hapikey: []
    post:
      tags:
      - Settings
      summary: Update the application settings
      description: Create or update the current settings for the application.
      operationId: CreateOrUpdateMarketingEventSettings
      security:
      - developer_hapikey: []
  /marketing/v3/marketing-events/events/search:
    get:
      tags:
      - Basic
      summary: Search for marketing events
      description: Search for marketing events that have an event id that starts with
        the query string
      operationId: SearchMarketingEvents
      security:
      - oauth2_legacy:
        - crm.objects.marketing_events.read
      - private_apps_legacy:
        - crm.objects.marketing_events.read
  /communication-preferences/v3/subscribe:
    post:
      tags:
      - Status
      summary: Subscribe a contact
      description: Subscribes a contact to the given subscription type. This API is
        not valid to use for subscribing a contact at a brand or portal level and
        will return an error.
      operationId: SubscribeContact
      security:
      - oauth2_legacy:
        - communication_preferences.write
      - oauth2_legacy:
        - communication_preferences.read_write
      - private_apps_legacy:
        - communication_preferences.write
      - private_apps_legacy:
        - communication_preferences.read_write
  /communication-preferences/v3/status/email/{emailAddress}:
    get:
      tags:
      - Status
      summary: Get subscription statuses for a contact
      description: Returns a list of subscriptions and their status for a given contact.
      operationId: ContactSubscriptionStatus
      security:
      - private_apps_legacy:
        - communication_preferences.read
      - oauth2_legacy:
        - communication_preferences.read_write
      - private_apps_legacy:
        - communication_preferences.read_write
      - oauth2_legacy:
        - communication_preferences.read
  /communication-preferences/v3/unsubscribe:
    post:
      tags:
      - Status
      summary: Unsubscribe a contact
      description: Unsubscribes a contact from the given subscription type. This API
        is not valid to use for unsubscribing a contact at a brand or portal level
        and will return an error.
      operationId: UnsubscribeContact
      security:
      - oauth2_legacy:
        - communication_preferences.write
      - oauth2_legacy:
        - communication_preferences.read_write
      - private_apps_legacy:
        - communication_preferences.write
      - private_apps_legacy:
        - communication_preferences.read_write
  /communication-preferences/v3/definitions:
    get:
      tags:
      - Definition
      summary: Get subscription definitions
      description: Get a list of all subscription definitions for the portal
      operationId: GetSubscriptionTypes
      security:
      - private_apps_legacy:
        - communication_preferences.read
      - oauth2_legacy:
        - communication_preferences.read_write
      - private_apps_legacy:
        - communication_preferences.read_write
      - oauth2_legacy:
        - communication_preferences.read
components:
  securitySchemes: {}