openapi: 3.0.1
info:
  title: HubSpot CRM Associations Schema
  version: v4
servers:
- url: https://api.hubapi.com
tags:
- name: Association Definition Configurations
- name: Definitions
paths:
  /crm/v4/associations/{fromObjectType}/{toObjectType}/labels:
    get:
      tags:
      - Definitions
      summary: Read
      description: Returns all association types between two object types
      operationId: GetAssociationTypeIdFromObjectToObject
      security:
      - oauth2_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.deals.read
      - private_apps:
        - crm.objects.orders.read
      - oauth2:
        - crm.objects.orders.read
      - private_apps:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.deals.read
      - private_apps_legacy:
        - contacts
      - oauth2:
        - crm.objects.subscriptions.read
      - private_apps:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.companies.read
      - private_apps_legacy:
        - crm.objects.goals.read
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - media_bridge.read
      - private_apps:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.companies.write
      - oauth2_legacy:
        - tickets
      - private_apps:
        - crm.objects.users.read
      - private_apps_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - oauth2_legacy:
        - crm.objects.goals.read
      - oauth2_legacy:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.commercepayments.read
      - private_apps:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.invoices.read
      - private_apps:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.quotes.write
      - private_apps:
        - crm.objects.quotes.write
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.leads.read
      - private_apps:
        - crm.objects.partner-clients.write
      - private_apps:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.line_items.read
      - private_apps:
        - crm.objects.leads.read
      - oauth2_legacy:
        - crm.objects.custom.read
      - private_apps_legacy:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.line_items.write
      - private_apps:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.carts.read
      - private_apps:
        - crm.objects.partner-clients.read
      - private_apps:
        - crm.objects.quotes.read
components:
  securitySchemes: {}