openapi: 3.0.1
info:
  title: HubSpot CRM
  version: v3
  description: ''
servers:
  - url: https://api.hubapi.com
paths:
#  /oauth/v1/access-tokens/{token}:
#    get:
#      tags:
#        - Access_Tokens
#      operationId: GetCurrentUserInfo
#      parameters:
#        - name: token
#          in: path
#          required: true
#          style: simple
#          explode: false
#          schema:
#            type: string
#      responses:
#        '200':
#          description: successful operation
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/AccessTokenInfoResponse'
#        default:
#          $ref: '#/components/responses/Error'
#      security: []
  /crm/v3/objects/calls/{callId}:
    get:
      tags:
        - Basic
      summary: Read
      description: Read an Object identified by `{callId}`. `{callId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.
      operationId: GetEngagementCallById
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
    delete:
      tags:
        - Basic
      summary: Archive
      description: Move an Object identified by `{callId}` to the recycling bin.
      operationId: DeleteEngagementCallById
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
    patch:
      tags:
        - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{callId}`or optionally a unique property value as specified by the `idProperty` query param. `{callId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.
      operationId: UpdateEngagementCallById
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/calls:
    post:
      tags:
        - Basic
      summary: Create
      description: Create a call with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard calls is provided.
      operationId: CreateEngagementCall
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/calls/search:
    post:
      tags:
        - Search
      summary: Search
      description: Search for a engagement calls using the query schema.
      operationId: SearchEngagementCalls
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/objects/emails/{emailId}:
    get:
      tags:
        - Basic
      summary: Read
      description: Read an Object identified by `{emailId}`. `{emailId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.
      operationId: GetEngagementEmailById
      security:
        - oauth2_legacy:
            - sales-email-read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps_legacy:
            - sales-email-read
        - private_apps:
            - crm.objects.contacts.read
    delete:
      tags:
        - Basic
      summary: Archive
      description: Move an Object identified by `{emailId}` to the recycling bin.
      operationId: DeleteEngagementEmailById
      security:
        - oauth2_legacy:
            - sales-email-read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps_legacy:
            - sales-email-read
        - private_apps:
            - crm.objects.contacts.write
    patch:
      tags:
        - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{emailId}`or optionally a unique property value as specified by the `idProperty` query param. `{emailId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.
      operationId: UpdateEngagementEmailById
      security:
        - oauth2_legacy:
            - sales-email-read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps_legacy:
            - sales-email-read
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/emails:
    post:
      tags:
        - Basic
      summary: Create
      description: Create a email with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard emails is provided.
      operationId: CreateEngagementEmail
      security:
        - oauth2_legacy:
            - sales-email-read
        - oauth2:
            - crm.objects.contacts.write
        - private_apps_legacy:
            - sales-email-read
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/emails/search:
    post:
      tags:
        - Search
      summary: Search
      description: Search for a engagement emails using the query schema.
      operationId: SearchEngagementEmails
      security:
        - oauth2_legacy:
            - sales-email-read
        - oauth2:
            - crm.objects.contacts.read
        - private_apps_legacy:
            - sales-email-read
        - private_apps:
            - crm.objects.contacts.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/objects/meetings/{meetingId}:
    get:
      tags:
        - Basic
      summary: Read
      description: Read an Object identified by `{meetingId}`. `{meetingId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.
      operationId: GetEngagementMeetingById
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
    delete:
      tags:
        - Basic
      summary: Archive
      description: Move an Object identified by `{meetingId}` to the recycling bin.
      operationId: DeleteEngagementMeetingById
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
    patch:
      tags:
        - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{meetingId}`. `{meetingId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.
      operationId: UpdateEngagementMeetingById
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/meetings:
    post:
      tags:
        - Basic
      summary: Create
      description: Create a meeting with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard meetings is provided.
      operationId: CreateEngagementMeeting
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/meetings/search:
    post:
      tags:
        - Search
      summary: Search
      description: Search for a engagement meetings using the query schema.
      operationId: SearchEngagementMeetings
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/objects/notes/{noteId}:
    get:
      tags:
        - Basic
      summary: Read
      description: Read an Object identified by `{noteId}`. `{noteId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.
      operationId: GetEngagementNoteById
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
    delete:
      tags:
        - Basic
      summary: Archive
      description: Move an Object identified by `{noteId}` to the recycling bin.
      operationId: DeleteEngagementNoteById
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
    patch:
      tags:
        - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{noteId}`. `{noteId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.
      operationId: UpdateEngagementNoteById
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/notes:
    post:
      tags:
        - Basic
      summary: Create
      description: Create a note with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard notes is provided.
      operationId: CreateEngagementNote
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/notes/search:
    post:
      tags:
        - Search
      summary: Search
      description: Search for engagement notes using the query schema.
      operationId: SearchEngagementNotes
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/objects/companies/{companyId}:
    get:
      tags:
        - Basic
      summary: Read
      description: Read an Object identified by `{companyId}`. `{companyId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.
      operationId: GetCompanyById
      security:
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.read
    delete:
      tags:
        - Basic
      summary: Archive
      description: Move an Object identified by `{companyId}` to the recycling bin.
      operationId: DeleteCompanyById
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
    patch:
      tags:
        - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{companyId}`. `{companyId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.
      operationId: UpdateCompanyById
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
  /crm/v3/objects/companies:
    post:
      tags:
        - Basic
      summary: Create
      description: Create a company with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard companies is provided.
      operationId: CreateCompany
      security:
        - oauth2:
            - crm.objects.companies.write
        - private_apps:
            - crm.objects.companies.write
  /crm/v3/objects/companies/search:
    post:
      tags:
        - Search
      summary: Search
      description: Search for companies using the query schema.
      operationId: SearchCompanies
      security:
        - oauth2:
            - crm.objects.companies.read
        - private_apps:
            - crm.objects.companies.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/objects/contacts/{contactId}:
    get:
      tags:
        - Basic
      summary: Read
      description: Read an Object identified by `{contactId}`. `{contactId}` refers to the internal object ID.  Control what is returned via the `properties` query param.
      operationId: GetContactById
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
    delete:
      tags:
        - Basic
      summary: Archive
      description: Move an Object identified by `{contactId}` to the recycling bin.
      operationId: DeleteContactById
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
    patch:
      tags:
        - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{contactId}`. `{contactId}` refers to the internal object ID. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.
      operationId: UpdateContactById
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/contacts:
    post:
      tags:
        - Basic
      summary: Create
      description: Create a contact with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard contacts is provided.
      operationId: CreateContact
      security:
        - oauth2:
            - crm.objects.contacts.write
        - private_apps:
            - crm.objects.contacts.write
  /crm/v3/objects/contacts/search:
    post:
      tags:
        - Search
      summary: Search
      description: Search for contacts using the query schema.
      operationId: SearchContacts
      security:
        - oauth2:
            - crm.objects.contacts.read
        - private_apps:
            - crm.objects.contacts.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/objects/deals/{dealId}:
    get:
      tags:
        - Basic
      summary: Read
      description: Read an Object identified by `{dealId}`. `{dealId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.
      operationId: GetDealById
      security:
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.deals.read
    delete:
      tags:
        - Basic
      summary: Archive
      description: Move an Object identified by `{dealId}` to the recycling bin.
      operationId: DeleteDealById
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
    patch:
      tags:
        - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{dealId}`. `{dealId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.
      operationId: UpdateDealById
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
  /crm/v3/objects/deals:
    post:
      tags:
        - Basic
      summary: Create
      description: Create a deal with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard deals is provided.
      operationId: CreateDeal
      security:
        - oauth2:
            - crm.objects.deals.write
        - private_apps:
            - crm.objects.deals.write
  /crm/v3/objects/deals/search:
    post:
      tags:
        - Search
      summary: Search
      description: Search for deals using the query schema.
      operationId: SearchDeals
      security:
        - oauth2:
            - crm.objects.deals.read
        - private_apps:
            - crm.objects.deals.read
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/lists/{listId}/memberships/add-and-remove:
    put:
      tags:
        - Memberships
      summary: Add and/or Remove Records from a List
      description: 'Add and/or remove records that have already been created in the system to and/or from a list.


        This endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.'
      operationId: AddAndRemoveContactsFromList
      security:
        - private_apps:
            - crm.lists.write
            - crm.lists.read
        - oauth2:
            - crm.lists.write
            - crm.lists.read
  /crm/v3/lists/{listId}:
    get:
      tags:
        - Lists
      summary: Fetch List by ID
      description: Fetch a single list by **ILS list ID**.
      operationId: GetListById
      security:
        - private_apps:
            - crm.lists.read
        - oauth2:
            - crm.lists.read
  /crm/v3/lists/search:
    post:
      tags:
        - Lists
      summary: Search Lists
      description: Search lists by list name or page through all lists by providing an empty `query` value.
      operationId: SearchLists
      security:
        - private_apps:
            - crm.lists.read
        - oauth2:
            - crm.lists.read
  /crm/v3/objects/tickets/{ticketId}:
    get:
      tags:
        - Basic
      summary: Read
      description: Read an Object identified by `{ticketId}`. `{ticketId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.
      operationId: GetTicketById
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets
    delete:
      tags:
        - Basic
      summary: Archive
      description: Move an Object identified by `{ticketId}` to the recycling bin.
      operationId: DeleteTicketById
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets
    patch:
      tags:
        - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{ticketId}`or optionally a unique property value as specified by the `idProperty` query param. `{ticketId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.
      operationId: UpdateTicketById
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets
  /crm/v3/objects/tickets:
    post:
      tags:
        - Basic
      summary: Create
      description: Create a ticket with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard tickets is provided.
      operationId: CreateTicket
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets
  /crm/v3/objects/tickets/search:
    post:
      tags:
        - Search
      summary: Search
      description: Search for tickets using the query schema.
      operationId: SearchTickets
      security:
        - oauth2_legacy:
            - tickets
        - private_apps_legacy:
            - tickets
      x-hubspot-rate-limit-exemptions:
        - ten-secondly
  /crm/v3/owners/:
    get:
      tags:
        - Owners
      summary: Get a page of owners
      operationId: GetPageOfOwners
      security:
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
  /crm/v3/owners/{ownerId}:
    get:
      tags:
        - Owners
      summary: Read an owner by given `id` or `userId`
      operationId: GetOwnerById
      security:
        - private_apps_legacy:
            - contacts
        - private_apps:
            - crm.objects.owners.read
        - oauth2:
            - crm.objects.owners.read
components:
  securitySchemes: {}
tags:
  - name: Owners
