openapi: 3.0.1
info:
  title: HubSpot CRM Write
  version: v3
  description: ''
servers:
- url: https://api.hubapi.com
paths:
  /crm/v3/objects/calls/{callId}:
    delete:
      tags:
      - Basic
      summary: Archive
      description: Move an Object identified by `{callId}` to the recycling bin.
      operationId: DeleteEngagementCallById
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
    patch:
      tags:
      - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{callId}`or
        optionally a unique property value as specified by the `idProperty` query
        param. `{callId}` refers to the internal object ID by default, and the `idProperty`
        query param refers to a property whose values are unique for the object. Provided
        property values will be overwritten. Read-only and non-existent properties
        will result in an error. Properties values can be cleared by passing an empty
        string.
      operationId: UpdateEngagementCallById
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
  /crm/v3/objects/calls:
    post:
      tags:
      - Basic
      summary: Create
      description: Create a call with the given properties and return a copy of the
        object, including the ID. Documentation and examples for creating standard
        calls is provided.
      operationId: CreateEngagementCall
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
  /crm/v3/objects/emails/{emailId}:
    delete:
      tags:
      - Basic
      summary: Archive
      description: Move an Object identified by `{emailId}` to the recycling bin.
      operationId: DeleteEngagementEmailById
      security:
      - oauth2_legacy:
        - sales-email-read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps_legacy:
        - sales-email-read
      - private_apps:
        - crm.objects.contacts.write
    patch:
      tags:
      - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{emailId}`or
        optionally a unique property value as specified by the `idProperty` query
        param. `{emailId}` refers to the internal object ID by default, and the `idProperty`
        query param refers to a property whose values are unique for the object. Provided
        property values will be overwritten. Read-only and non-existent properties
        will result in an error. Properties values can be cleared by passing an empty
        string.
      operationId: UpdateEngagementEmailById
      security:
      - oauth2_legacy:
        - sales-email-read
      - oauth2:
        - crm.objects.contacts.write
      - private_apps_legacy:
        - sales-email-read
      - private_apps:
        - crm.objects.contacts.write
  /crm/v3/objects/meetings/{meetingId}:
    delete:
      tags:
      - Basic
      summary: Archive
      description: Move an Object identified by `{meetingId}` to the recycling bin.
      operationId: DeleteEngagementMeetingById
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
    patch:
      tags:
      - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{meetingId}`.
        `{meetingId}` refers to the internal object ID by default, or optionally any
        unique property value as specified by the `idProperty` query param. Provided
        property values will be overwritten. Read-only and non-existent properties
        will be ignored. Properties values can be cleared by passing an empty string.
      operationId: UpdateEngagementMeetingById
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
  /crm/v3/objects/meetings:
    post:
      tags:
      - Basic
      summary: Create
      description: Create a meeting with the given properties and return a copy of
        the object, including the ID. Documentation and examples for creating standard
        meetings is provided.
      operationId: CreateEngagementMeeting
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
  /crm/v3/objects/notes/{noteId}:
    delete:
      tags:
      - Basic
      summary: Archive
      description: Move an Object identified by `{noteId}` to the recycling bin.
      operationId: DeleteEngagementNoteById
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
    patch:
      tags:
      - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{noteId}`.
        `{noteId}` refers to the internal object ID by default, or optionally any
        unique property value as specified by the `idProperty` query param. Provided
        property values will be overwritten. Read-only and non-existent properties
        will be ignored. Properties values can be cleared by passing an empty string.
      operationId: UpdateEngagementNoteById
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
  /crm/v3/objects/companies/{companyId}:
    delete:
      tags:
      - Basic
      summary: Archive
      description: Move an Object identified by `{companyId}` to the recycling bin.
      operationId: DeleteCompanyById
      security:
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.companies.write
    patch:
      tags:
      - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{companyId}`.
        `{companyId}` refers to the internal object ID by default, or optionally any
        unique property value as specified by the `idProperty` query param. Provided
        property values will be overwritten. Read-only and non-existent properties
        will be ignored. Properties values can be cleared by passing an empty string.
      operationId: UpdateCompanyById
      security:
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.companies.write
  /crm/v3/objects/companies:
    post:
      tags:
      - Basic
      summary: Create
      description: Create a company with the given properties and return a copy of
        the object, including the ID. Documentation and examples for creating standard
        companies is provided.
      operationId: CreateCompany
      security:
      - oauth2:
        - crm.objects.companies.write
      - private_apps:
        - crm.objects.companies.write
  /crm/v3/objects/contacts/{contactId}:
    delete:
      tags:
      - Basic
      summary: Archive
      description: Move an Object identified by `{contactId}` to the recycling bin.
      operationId: DeleteContactById
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
    patch:
      tags:
      - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{contactId}`.
        `{contactId}` refers to the internal object ID. Provided property values will
        be overwritten. Read-only and non-existent properties will be ignored. Properties
        values can be cleared by passing an empty string.
      operationId: UpdateContactById
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
  /crm/v3/objects/contacts:
    post:
      tags:
      - Basic
      summary: Create
      description: Create a contact with the given properties and return a copy of
        the object, including the ID. Documentation and examples for creating standard
        contacts is provided.
      operationId: CreateContact
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
  /crm/v3/objects/deals/{dealId}:
    delete:
      tags:
      - Basic
      summary: Archive
      description: Move an Object identified by `{dealId}` to the recycling bin.
      operationId: DeleteDealById
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
    patch:
      tags:
      - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{dealId}`.
        `{dealId}` refers to the internal object ID by default, or optionally any
        unique property value as specified by the `idProperty` query param. Provided
        property values will be overwritten. Read-only and non-existent properties
        will be ignored. Properties values can be cleared by passing an empty string.
      operationId: UpdateDealById
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
  /crm/v3/objects/deals:
    post:
      tags:
      - Basic
      summary: Create
      description: Create a deal with the given properties and return a copy of the
        object, including the ID. Documentation and examples for creating standard
        deals is provided.
      operationId: CreateDeal
      security:
      - oauth2:
        - crm.objects.deals.write
      - private_apps:
        - crm.objects.deals.write
  /crm/v3/lists/{listId}/memberships/add-and-remove:
    put:
      tags:
      - Memberships
      summary: Add and/or Remove Records from a List
      description: 'Add and/or remove records that have already been created in the
        system to and/or from a list.


        This endpoint only works for lists that have a `processingType` of `MANUAL`
        or `SNAPSHOT`.'
      operationId: AddAndRemoveContactsFromList
      security:
      - private_apps:
        - crm.lists.write
        - crm.lists.read
      - oauth2:
        - crm.lists.write
        - crm.lists.read
  /crm/v3/objects/tickets/{ticketId}:
    delete:
      tags:
      - Basic
      summary: Archive
      description: Move an Object identified by `{ticketId}` to the recycling bin.
      operationId: DeleteTicketById
      security:
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - tickets
    patch:
      tags:
      - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{ticketId}`or
        optionally a unique property value as specified by the `idProperty` query
        param. `{ticketId}` refers to the internal object ID by default, and the `idProperty`
        query param refers to a property whose values are unique for the object. Provided
        property values will be overwritten. Read-only and non-existent properties
        will result in an error. Properties values can be cleared by passing an empty
        string.
      operationId: UpdateTicketById
      security:
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - tickets
  /crm/v3/objects/tickets:
    post:
      tags:
      - Basic
      summary: Create
      description: Create a ticket with the given properties and return a copy of
        the object, including the ID. Documentation and examples for creating standard
        tickets is provided.
      operationId: CreateTicket
      security:
      - oauth2_legacy:
        - tickets
      - private_apps_legacy:
        - tickets
  /crm/v3/objects/tasks/{taskId}:
    delete:
      tags:
      - Basic
      summary: Archive
      description: Move an Object identified by `{taskId}` to the recycling bin.
      operationId: DeleteTaskById
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
    patch:
      tags:
      - Basic
      summary: Update
      description: Perform a partial update of an Object identified by `{taskId}`.
        `{taskId}` refers to the internal object ID by default, or optionally any
        unique property value as specified by the `idProperty` query param. Provided
        property values will be overwritten. Read-only and non-existent properties
        will be ignored. Properties values can be cleared by passing an empty string.
      operationId: UpdateTaskById
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
  /crm/v3/objects/tasks:
    post:
      tags:
      - Basic
      summary: Create
      description: Create a task with the given properties and return a copy of the
        object, including the ID. Documentation and examples for creating standard
        tasks is provided.
      operationId: CreateTask
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
  /crm/v3/properties/{objectType}/groups/{groupName}:
    delete:
      tags:
      - Groups
      summary: Archive a property group
      description: Move a property group identified by {groupName} to the recycling
        bin.
      operationId: DeletePropertyGroupByName
      security:
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - crm.pipelines.orders.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps_legacy:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.carts.write
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - crm.schemas.companies.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps:
        - crm.schemas.deals.write
    patch:
      tags:
      - Groups
      summary: Update a property group
      description: Perform a partial update of a property group identified by {groupName}.
        Provided fields will be overwritten.
      operationId: UpdatePropertyGroupByName
      security:
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - crm.pipelines.orders.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps_legacy:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.carts.write
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - crm.schemas.companies.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps:
        - crm.schemas.deals.write
  /crm/v3/properties/{objectType}/{propertyName}:
    delete:
      tags:
      - Core
      summary: Archive a property
      description: Move a property identified by {propertyName} to the recycling bin.
      operationId: DeletePropertyByName
      security:
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - crm.pipelines.orders.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps_legacy:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.carts.write
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - crm.schemas.companies.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps:
        - crm.schemas.deals.write
    patch:
      tags:
      - Core
      summary: Update a property
      description: Perform a partial update of a property identified by {propertyName}.
        Provided fields will be overwritten.
      operationId: UpdatePropertyByName
      security:
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - crm.pipelines.orders.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps_legacy:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.carts.write
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - crm.schemas.companies.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps:
        - crm.schemas.deals.write
  /crm/v3/properties/{objectType}:
    post:
      tags:
      - Core
      summary: Create a property
      description: Create and return a copy of a new property for the specified object
        type.
      operationId: CreateProperty
      security:
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - crm.pipelines.orders.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps_legacy:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.carts.write
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - crm.schemas.companies.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps:
        - crm.schemas.deals.write
  /crm/v3/properties/{objectType}/groups:
    post:
      tags:
      - Groups
      summary: Create a property group
      description: Create and return a copy of a new property group.
      operationId: CreatePropertyGroup
      security:
      - private_apps:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.orders.write
      - private_apps:
        - crm.schemas.orders.write
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.schemas.contacts.write
      - oauth2_legacy:
        - crm.pipelines.orders.write
      - private_apps_legacy:
        - contacts
      - private_apps:
        - crm.schemas.contacts.write
      - oauth2:
        - crm.schemas.carts.write
      - private_apps:
        - crm.objects.users.write
      - private_apps_legacy:
        - crm.schemas.custom.write
      - private_apps_legacy:
        - crm.pipelines.orders.write
      - private_apps:
        - crm.schemas.carts.write
      - oauth2_legacy:
        - tickets
      - oauth2:
        - crm.schemas.deals.write
      - oauth2:
        - crm.objects.users.write
      - private_apps_legacy:
        - e-commerce
      - oauth2:
        - crm.schemas.companies.write
      - private_apps:
        - crm.schemas.companies.write
      - private_apps:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2_legacy:
        - e-commerce
      - private_apps_legacy:
        - tickets
      - private_apps:
        - crm.schemas.deals.write
components:
  securitySchemes: {}
tags:
- name: Batch
- name: Groups
- name: Core
